### ISSUE TITLE
标题过长时，左右固定列的top属性计算错误

### ISSUE THREAD

**Issue by jardn** [qiuyaofan/jqTable#4]
`<div class="c-table c-table--border">
                    <table cellspacing="0" cellpadding="0" role="c-table">
                        <colgroup>
                            <col name="" width="35">
                            <col name="" width="130">
                            <col name="" width="130">
                            <col name="" width="200">
                            <col name="" width="100">
                            <col name="" width="130">
                            <col name="" width="">
                            <col name="" width="">
                            <col name="" width="140">
                            <col name="" width="100">
                        </colgroup>
                        <thead>
                            <tr>
                                <th>
                                    <div class="cell">
                                        #
                                    </div>
                                </th>
                                <th>
                                    <div class="cell">单据类型</div>
                                </th>
                                <th>
                                    <div class="cell">单号</div>
                                </th>
                                <th>
                                    <div class="cell">事由</div>
                                </th>
                                <th>
                                    <div class="cell">报销/申请人</div>
                                </th>
                                <th>
                                    <div class="cell">报销/申请金额</div>
                                </th>
                                <th>
                                    <div class="cell">报销/申请机构</div>
                                </th>
                                <th>
                                    <div class="cell">报销/申请部门</div>
                                </th>
                                <th>
                                    <div class="cell">到达时间</div>
                                </th>
                                <th>
                                    <div class="cell">报销状态</div>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr class="pointer btn-show-details">
                                <td>
                                    <div class="cell">
                                        <div class="checkbox form-checkbox">
                                            <label>
                                                <input type="checkbox" class="g-selectAll--input" data-value="100">
                                            </label>
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    <div class="cell" data-id="1">
                                        普通报销
                                    </div>
                                </td>
                                <td>
                                    <div class="cell">
                                        MK119081323
                                    </div>
                                </td>
                                <td>
                                    <div class="cell">
                                        测试一下
                                    </div>
                                </td>
                                <td>
                                    <div class="cell">
                                        冯涛
                                    </div>
                                </td>
                                <td>
                                    <div class="cell">
                                        ￥ 500.00
                                    </div>
                                </td>
                                <td>
                                    <div class="cell">
                                        龙岩支行
                                    </div>
                                </td>
                                <td>
                                    <div class="cell">
                                        办公室
                                    </div>
                                </td>
                                <td>
                                    <div class="cell">
                                        2019-01-01 15:10
                                    </div>
                                </td>
                                <td>
                                    <div class="cell">
                                        <span class="label label-warning">审批中</span>
                                    </div>
                                </td>
                            </tr>
                            <tr class="pointer btn-show-details">
                                <td>
                                    <div class="cell">
                                        <div class="checkbox form-checkbox">
                                            <label>
                                                <input type="checkbox" class="g-selectAll--input" data-value="100">
                                            </label>
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    <div class="cell" data-id="1">
                                        普通报销
                                    </div>
                                </td>
                                <td>
                                    <div class="cell">
                                        MK119081323
                                    </div>
                                </td>
                                <td>
                                    <div class="cell">
                                        测试一下
                                    </div>
                                </td>
                                <td>
                                    <div class="cell">
                                        冯涛
                                    </div>
                                </td>
                                <td>
                                    <div class="cell">
                                        ￥ 500.00
                                    </div>
                                </td>
                                <td>
                                    <div class="cell">
                                        龙岩支行
                                    </div>
                                </td>
                                <td>
                                    <div class="cell">
                                        营业部
                                    </div>
                                </td>
                                <td>
                                    <div class="cell">
                                        2019-01-01 15:10
                                    </div>
                                </td>
                                <td>
                                    <div class="cell">
                                        <span class="label label-warning">审批中</span>
                                    </div>
                                </td>
                            </tr>
                            
                        </tbody>
                    </table>
                </div>`

**Comment by jardn** [comment]
固定列的时候，如果其中一列设为自适应 也就是 
```
<colgroup>
    <col name="" width="35">
    <col name="" width="">
    <col name="" width="">
    <col name="" width="140">
</colgroup>

<thead>
    <tr>
        <th>
            <div class="cell">机构</div>
        </th>
        <th>
            <div class="cell">凭证号</div>
        </th>
        <th>
            <div class="cell">摘要</div>
        </th>
        <th>
            <div class="cell">摘要</div>
        </th>
    </tr>
</thead>
```
这个时候左右固定列的 style：top 和height都计算错误，可能是计算th高度的时候出错！
问题应该是th里面的cell问题，具体什么原因不清楚。
解决办法：
去掉里面的div.cell，tr加个class padding

```
tr.padding th {
    padding-left: 12px;
    padding-right: 12px;
}
<thead>
    <tr class="padding">
        <th>机构</th>
        <th>机构</th>
        <th>机构</th>
        ....
    </tr>
</thead>
```

**Comment by qiuyaofan** [comment]
问题描述不清晰，关闭处理
